services:
  handler:
    build: ./handler
    volumes:
      - logs:/logs
    ports:
      - 80:80
      - 443:443
    environment:
      - CA_PRIVATE_KEY_NAME=${CA_PRIVATE_KEY_NAME}
      - CA_CERTIFICATE_NAME=${CA_CERTIFICATE_NAME}
      - LOCAL_SERVER=${LOCAL_SERVER}
      - DEBUG=${DEBUG}

volumes:
  logs: